#!/bin/bash

intltool-extract --type=gettext/glade share/mintstick/mintstick.glade
xgettext --language=Python --keyword=_ --keyword=N_ --output=mintstick.pot lib/mintstick.py generate_additional_files.py share/mintstick/mintstick.glade.h
rm -f share/mintstick/mintstick.glade.h
