#!/bin/sh

#intltool-extract --type=gettext/glade usr/share/linuxmint/mintstick/mintstick.glade
xgettext --language=Python --keyword=_ --keyword=N_ --output=mintstick.pot \
usr/share/linuxmint/mintstick/mintstick.py generate_additional_files.py #\
#usr/share/linuxmint/mintstick/mintstick.glade.h
#rm -f usr/share/linuxmint/mintstick/mintstick.glade.h
