.TH IMAGEWRITER "1" "April 2009" "imagewriter " "User Commands"

.SH NAME
imagewriter \- gui only application to write .img files to USB keys

.SH DESCRIPTION
.B imagewriter
is a graphical application to write .img files to USB keys.

.SH "SEE ALSO"
The full documentation for
.B imagewriter
is maintained at https://launchpad.net/usb-imagewriter. 
The application has no options and should not be used from the 
commandline.
.PP
Go to the project page to get access to the complete documentation.

